version: "3"
services:
  db:
    container_name: awesome-events-mysql
    image: mysql:8.0.36-bookworm
    platform: linux/amd64
    command: ["--default-authentication-plugin=mysql_native_password"]
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app
      MYSQL_PASSWORD: docker
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
    driver: local
