name: Build Backend

on:
  push:
    tags:
      - v*

jobs:
  backend-build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      actions: read

    steps:
      - uses: actions/checkout@v4.1.1

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.2.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: ap-southeast-1
          audience: sts.amazonaws.com
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github_actions_role

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build nginx and push image to AWS ECR
        uses: docker/build-push-action@v5
        with:
          file: docker/nginx/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/awesome-events-nginx:$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")

      - name: Build app and push image to AWS ECR
        uses: docker/build-push-action@v5
        with:
          file: docker/app/Dockerfile
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/awesome-events-app:$(echo ${{ github.ref }} | sed -e "s#refs/tags/##g")
